###########################
# VME pins
###########################

set_property package_pin    V31         [get_ports vme_data[0]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[0]]
set_property package_pin    W31         [get_ports vme_data[1]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[1]]
set_property package_pin    V32         [get_ports vme_data[2]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[2]]
set_property package_pin    U34         [get_ports vme_data[3]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[3]]
set_property package_pin    V34         [get_ports vme_data[4]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[4]]
set_property package_pin    Y31         [get_ports vme_data[5]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[5]]
set_property package_pin    Y32         [get_ports vme_data[6]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[6]]
set_property package_pin    V33         [get_ports vme_data[7]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[7]]
set_property package_pin    W34         [get_ports vme_data[8]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[8]]
set_property package_pin    W30         [get_ports vme_data[9]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[9]]
set_property package_pin    Y30         [get_ports vme_data[10]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[10]]
set_property package_pin    W33         [get_ports vme_data[11]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[11]]
set_property package_pin    Y33         [get_ports vme_data[12]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[12]]
set_property package_pin    AC33        [get_ports vme_data[13]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[13]]
set_property package_pin    AD33        [get_ports vme_data[14]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[14]]
set_property package_pin    AA34        [get_ports vme_data[15]]
set_property IOSTANDARD     LVCMOS18    [get_ports vme_data[15]]

set_property PACKAGE_PIN     AK30       [get_ports vme_addr[1]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[1]]
set_property PACKAGE_PIN     AL30       [get_ports vme_addr[2]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[2]]
set_property PACKAGE_PIN     AM30       [get_ports vme_addr[3]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[3]]
set_property PACKAGE_PIN     AM31       [get_ports vme_addr[4]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[4]]
set_property PACKAGE_PIN     AL29       [get_ports vme_addr[5]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[5]]
set_property PACKAGE_PIN     AM29       [get_ports vme_addr[6]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[6]]
set_property PACKAGE_PIN     AN29       [get_ports vme_addr[7]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[7]]
set_property PACKAGE_PIN     AP30       [get_ports vme_addr[8]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[8]]
set_property PACKAGE_PIN     AN27       [get_ports vme_addr[9]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[9]]
set_property PACKAGE_PIN     AN28       [get_ports vme_addr[10]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[10]]
set_property PACKAGE_PIN     AP28       [get_ports vme_addr[11]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[11]]
set_property PACKAGE_PIN     AP29       [get_ports vme_addr[12]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[12]]
set_property PACKAGE_PIN     AN26       [get_ports vme_addr[13]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[13]]
set_property PACKAGE_PIN     AP26       [get_ports vme_addr[14]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[14]]
set_property PACKAGE_PIN     AJ28       [get_ports vme_addr[15]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[15]]
set_property PACKAGE_PIN     AK28       [get_ports vme_addr[16]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[16]]
set_property PACKAGE_PIN     AH27       [get_ports vme_addr[17]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[17]]
set_property PACKAGE_PIN     AH28       [get_ports vme_addr[18]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[18]]
set_property PACKAGE_PIN     AL27       [get_ports vme_addr[19]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[19]]
set_property PACKAGE_PIN     AL28       [get_ports vme_addr[20]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[20]]
set_property PACKAGE_PIN     AK26       [get_ports vme_addr[21]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[21]]
set_property PACKAGE_PIN     AK27       [get_ports vme_addr[22]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[22]]
set_property PACKAGE_PIN     AM26       [get_ports vme_addr[23]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_addr[23]]

set_property PACKAGE_PIN     AL33       [get_ports vme_am[0]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[0]]
set_property PACKAGE_PIN     AH34       [get_ports vme_am[1]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[1]]
set_property PACKAGE_PIN     AJ34       [get_ports vme_am[2]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[2]]
set_property PACKAGE_PIN     AH31       [get_ports vme_am[3]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[3]]
set_property PACKAGE_PIN     AH32       [get_ports vme_am[4]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[4]]
set_property PACKAGE_PIN     AH33       [get_ports vme_am[5]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_am[5]]

set_property PACKAGE_PIN     AB34       [get_ports vme_gap_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_gap_b]

set_property PACKAGE_PIN     AB30       [get_ports vme_ga_b[0]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ga_b[0]]
set_property PACKAGE_PIN     AD34       [get_ports vme_ga_b[1]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ga_b[1]]
set_property PACKAGE_PIN     AC34       [get_ports vme_ga_b[2]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ga_b[2]]
set_property PACKAGE_PIN     AB29       [get_ports vme_ga_b[3]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ga_b[3]]
set_property PACKAGE_PIN     AA29       [get_ports vme_ga_b[4]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ga_b[4]]

set_property PACKAGE_PIN     AJ31       [get_ports vme_as_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_as_b]

set_property PACKAGE_PIN     AJ30       [get_ports vme_ds_b[0]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ds_b[0]]
set_property PACKAGE_PIN     AJ33       [get_ports vme_ds_b[1]]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_ds_b[1]]

set_property PACKAGE_PIN     AC32       [get_ports vme_sysfail_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_sysfail_b]

set_property PACKAGE_PIN     AB32       [get_ports vme_berr_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_berr_b]

set_property PACKAGE_PIN     AB31       [get_ports vme_iack_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_iack_b]

set_property PACKAGE_PIN     AA32       [get_ports vme_lword_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_lword_b]

set_property PACKAGE_PIN     AA33       [get_ports vme_write_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_write_b]

set_property PACKAGE_PIN     AN23       [get_ports kus_vme_oe_b]
set_property IOSTANDARD      LVCMOS18   [get_ports kus_vme_oe_b]

set_property PACKAGE_PIN     AP23       [get_ports kus_vme_dir_b]
set_property IOSTANDARD      LVCMOS18   [get_ports kus_vme_dir_b]

set_property PACKAGE_PIN     AM25       [get_ports vme_dtack_kus_b]
set_property IOSTANDARD      LVCMOS18   [get_ports vme_dtack_kus_b]

set_property PACKAGE_PIN     AN23       [get_ports ]
set_property IOSTANDARD      LVCMOS18   [get_ports ]

set_property PACKAGE_PIN     AN23       [get_ports ]
set_property IOSTANDARD      LVCMOS18   [get_ports ]

set_property PACKAGE_PIN     AN23       [get_ports ]
set_property IOSTANDARD      LVCMOS18   [get_ports ]

set_property PACKAGE_PIN     AN23       [get_ports ]
set_property IOSTANDARD      LVCMOS18   [get_ports ]

###########################
# DCFEB pins
###########################
set_property PACKAGE_PIN     F15       [get_ports dcfeb_tck_p[1]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[1]]
set_property PACKAGE_PIN     F14       [get_ports dcfeb_tck_n[1]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[1]]
set_property PACKAGE_PIN     D19       [get_ports dcfeb_tck_p[2]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[2]]
set_property PACKAGE_PIN     D18       [get_ports dcfeb_tck_n[2]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[2]]
set_property PACKAGE_PIN     D14       [get_ports dcfeb_tck_p[3]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[3]]
set_property PACKAGE_PIN     C14       [get_ports dcfeb_tck_n[3]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[3]]
set_property PACKAGE_PIN     E15       [get_ports dcfeb_tck_p[4]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[4]]
set_property PACKAGE_PIN     D15       [get_ports dcfeb_tck_n[4]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[4]]
set_property PACKAGE_PIN     B17       [get_ports dcfeb_tck_p[5]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[5]]
set_property PACKAGE_PIN     B16       [get_ports dcfeb_tck_n[5]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[5]]
set_property PACKAGE_PIN     C18       [get_ports dcfeb_tck_p[6]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[6]]
set_property PACKAGE_PIN     C17       [get_ports dcfeb_tck_n[6]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[6]]
set_property PACKAGE_PIN     C19       [get_ports dcfeb_tck_p[7]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_p[7]]
set_property PACKAGE_PIN     B19       [get_ports dcfeb_tck_n[7]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tck_n[7]]

set_property PACKAGE_PIN     A19       [get_ports dcfeb_tms_p]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tms_p]
set_property PACKAGE_PIN     A18       [get_ports dcfeb_tms_n]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tms_n]

set_property PACKAGE_PIN     B14       [get_ports dcfeb_tdi_p]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdi_p]
set_property PACKAGE_PIN     A14       [get_ports dcfeb_tdi_n]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdi_n]

set_property PACKAGE_PIN     F23       [get_ports dcfeb_tdo_p[1]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[1]]
set_property PACKAGE_PIN     F24       [get_ports dcfeb_tdo_n[1]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[1]]
set_property PACKAGE_PIN     D20       [get_ports dcfeb_tdo_p[2]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[2]]
set_property PACKAGE_PIN     D21       [get_ports dcfeb_tdo_n[2]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[2]]
set_property PACKAGE_PIN     G20       [get_ports dcfeb_tdo_p[3]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[3]]
set_property PACKAGE_PIN     F20       [get_ports dcfeb_tdo_n[3]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[3]]
set_property PACKAGE_PIN     G24       [get_ports dcfeb_tdo_p[4]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[4]]
set_property PACKAGE_PIN     F25       [get_ports dcfeb_tdo_n[4]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[4]]
set_property PACKAGE_PIN     G22       [get_ports dcfeb_tdo_p[5]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[5]]
set_property PACKAGE_PIN     F22       [get_ports dcfeb_tdo_n[5]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[5]]
set_property PACKAGE_PIN     E20       [get_ports dcfeb_tdo_p[6]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[6]]
set_property PACKAGE_PIN     E21       [get_ports dcfeb_tdo_n[6]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[6]]
set_property PACKAGE_PIN     J19       [get_ports dcfeb_tdo_p[7]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_p[7]]
set_property PACKAGE_PIN     J18       [get_ports dcfeb_tdo_n[7]]
set_property IOSTANDARD      LVDS      [get_ports dcfeb_tdo_n[7]]

set_property PACKAGE_PIN     G19       [get_ports dcfeb_done[1]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[1]]
set_property PACKAGE_PIN     F19       [get_ports dcfeb_done[2]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[2]]
set_property PACKAGE_PIN     G15       [get_ports dcfeb_done[3]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[3]]
set_property PACKAGE_PIN     G14       [get_ports dcfeb_done[4]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[4]]
set_property PACKAGE_PIN     F18       [get_ports dcfeb_done[5]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[5]]
set_property PACKAGE_PIN     F17       [get_ports dcfeb_done[6]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[6]]
set_property PACKAGE_PIN     H14       [get_ports dcfeb_done[7]]
set_property IOSTANDARD      LVCMOS18  [get_ports dcfeb_done[7]]


###########################
# Config pins
###########################

set_property PACKAGE_PIN U21        [get_ports KUS_DL_SEL]
set_property IOSTANDARD LVCMOS18    [get_ports KUS_DL_SEL]

set_property PACKAGE_PIN T23        [get_ports FPGA_SEL_18]
set_property IOSTANDARD LVCMOS18    [get_ports FPGA_SEL_18]

set_property PACKAGE_PIN W29        [get_ports RST_CLKS_18_B]
set_property IOSTANDARD LVCMOS18    [get_ports RST_CLKS_18_B]

set_property PACKAGE_PIN L9         [get_ports DONE]
set_property IOSTANDARD LVCMOS18    [get_ports DONE]
