create_hw_probe -map {probe0[0]}      tx_reset_done                    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[1]}      txfsm_reset_done                 [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[2]}      gtwiz_userclk_tx_active_int      [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[3]}      gtwiz_buffbypass_tx_reset_in_s   [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[4]}      MGT_TXRESET_i                    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[5]}      gtwiz_userclk_tx_reset_int       [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[6]}      resetGtxTx_from_rxBitSlipControl [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[7]}      rx_reset_done                    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[8]}      rxfsm_reset_done                 [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[9]}      gtwiz_userclk_rx_active_int      [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[10]}     gtwiz_buffbypass_rx_reset_in_s   [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[11]}     MGT_RXRESET_i                    [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[12]}     gtwiz_userclk_rx_reset_int       [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[13]}     resetGtxRx_from_rxBitSlipControl [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[14]}     done_from_rxBitSlipControl       [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[15]}     ready_from_bitSlipCtrller        [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[16]}     rxBitSlip_to_gtx                 [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[17]}     mgtRst_from_bitslipCtrl          [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[18]}     MGT_AUTORSTEn_i                  [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[19]}     MGT_AUTORSTONEVEN_i              [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[20]}     rx_headerlocked_s                [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[21]}     rx_bitslipIsEven_s               [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[61:22]}  MGT_USRWORD_s[39:0]              [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[63:62]}  patSer_state[1:0]                [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[65:64]}  patSer_psAddress[1:0]            [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[66]}     patSer_shiftPsAddr               [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[67]}     patSer_headerFlag                [get_hw_ilas hw_ila_1]
create_hw_probe -map {probe0[25:22]}  MGT_USRWORD_header[3:0]          [get_hw_ilas hw_ila_1]



